# RL-Games SAC configuration for F1TENTH racing
# Based on IsaacGymEnvs AntSAC configuration
# https://github.com/isaac-sim/IsaacGymEnvs/blob/main/isaacgymenvs/cfg/train/AntSAC.yaml

params:
  seed: 42

  algo:
    name: sac  # Soft Actor-Critic algorithm

  model:
    name: soft_actor_critic

  env:
    clip_observations: 5.0
    clip_actions: 1.0

  network:
    name: actor_critic
    separate: True  # SAC requires separate actor and critic networks

    space:
      continuous:
        mu_activation: None
        sigma_activation: None
        mu_init:
          name: default
        sigma_init:
          name: const_initializer
          val: 0.0
        fixed_sigma: False

    mlp:
      units: [512, 512, 256]  # Same as skrl: 3 hidden layers
      activation: relu
      d2rl: False

      initializer:
        name: default
      regularizer:
        name: None

    log_std_bounds: [-5, 2]

  load_checkpoint: False
  load_path: ""

  config:
    name: f1tenth_sac
    env_name: rlgpu
    device: 'cuda:3'
    device_name: 'cuda:3'
    multi_gpu: False
    ppo: False
    mixed_precision: False
    normalize_input: True
    normalize_value: False
    num_actors: -1
    reward_shaper:
      scale_value: 1.0
    gamma: 0.99
    score_to_win: 20000
    max_epochs: 20000
    save_best_after: 50
    save_frequency: 500
    print_stats: True
    grad_norm: 1.0
    truncate_grads: True

    # SAC specific parameters (required by rl_games SAC agent)
    batch_size: 128
    num_warmup_steps: 10
    replay_buffer_size: 100000
    critic_tau: 0.005  # Soft update coefficient for target networks
    init_alpha: 1.0  # Initial temperature parameter
    learnable_temperature: True  # Whether to learn temperature
    actor_lr: 5.0e-4  # Actor learning rate
    critic_lr: 5.0e-4  # Critic learning rate
    alpha_lr: 5.0e-3  # Temperature learning rate
